version: '3'
services:
  superresolution:
    image: "s2-superresolution:latest"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 20G
        reservations:
          cpus: '0.50'
          memory: 150M
    environment:
      UP42_TASK_PARAMETERS: '{"copy_original_bands": false}'
    volumes:
      - /tmp/e2e_s2-superresolution:/tmp
